"""test

Revision ID: 863ed4f257de
Revises: 0e12555d4c52
Create Date: 2023-09-16 17:45:44.356498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863ed4f257de'
down_revision = '0e12555d4c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
